/* tslint:disable */
/* eslint-disable */
/**
 * Simple Crud Api For Case Studies
 *  ## Endpoints are protected by Basic Authentication    ###  Credentials     * **Username:** demo * **Password:** demo  [Figma file link](/static/Crud-Operations.fig)  #    > **If you prefer _ReDoc:_** [Redoc Documentation](/redoc) 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

